require_relative 'wordsmith/generator'
require_relative 'wordsmith/version'
require_relative 'wordsmith/project'
require_relative 'wordsmith/template'
require_relative 'wordsmith/template_collection'
require_relative 'wordsmith/configuration'
require_relative 'wordsmith/client'
